### ISSUE TITLE
Grave being replaced when dying by a dragon from "Ice and Fire" mod

### ISSUE THREAD

**Issue by Sheppard22** [Corail31/tombstone_lite#17]
(Sorry for opening a new discussion)

Hi again! i don't really know if i must create a new issue or just writte here even though it's labeled as "closed", but the bug is still there.

I think i know what happens (This time a Green Dragon killed me with fire) When this dragons throws fire, blocks affected by it turns into "Charred Stone" (A block from ice & fire). I have my death's waypoint inside this block so i think it makes sense that the grave has been replaced by Charred Stone.

I took some screenshots:

![2018-01-08_15 41 37](https://user-images.githubusercontent.com/34324441/34704479-195ce5de-f4d8-11e7-846d-2e9b01fe7f0f.png)

![2018-01-08_15 42 44](https://user-images.githubusercontent.com/34324441/34704483-1a1bd700-f4d8-11e7-81fb-7fdbd99d6c57.png)

Happened to her too:
![2018-01-08_15 43 51](https://user-images.githubusercontent.com/34324441/34704484-1b57392a-f4d8-11e7-8cf5-a826066509b4.png)

**Comment by Corail31** [comment]
You should report this bug to "fire & ice", because the mod seems not reliable (btw, this mod makes cascading world lag with chunk, and flood the logs), it's not normal if they replace blocks without checking at least the hardness return -1 (indestructible) or canDestroyBlock()

**Comment by Corail31** [comment]
https://github.com/Alex-the-666/Ice_and_Fire/issues/416

**Comment by Corail31** [comment]
should be fixed in 2.3.0 (by removing affected graves in the detonate event)

**Comment by Sheppard22** [comment]
Hi! Thanks for working on the problem! I saw that bug report on Ice&fire github so i didn't create a new issue, but many thanks!

**Comment by Corail31** [comment]
if you could check if this event is enough to prevent the graves to be charred, because i haven't the time to make any try about it.

**Comment by Corail31** [comment]
@Sheppard22 : i'm waiting to know if all is good now ;)

**Comment by NotAVerb** [comment]
I'm using Tombstone 2.3.0 and Ice&Fire 1.3.1.
The problem seems to have persisted. I died to a young dragon's breath attack and re-spawned without a key.

**Comment by Corail31** [comment]
But the grave was replaced? because the grave & key only appears when you have at least one item on you.

**Comment by Sheppard22** [comment]
Hi! Sorry for the delay.  In version 2.2.0, i was slain by a dragon and the grave wasn't replaced. Problem is, my friend died too and she didn't find her grave/missing key. Sorry we did not check if it was replaced. Anyways it seems it's not over yet, i'll try with next release! Thanks

**Comment by Corail31** [comment]
yes i know why, i fixed it in : https://github.com/Corail31/tombstone_lite/commit/87657529b8c017f66a4b80d3c006f833f8a67046
and i set the event priority to highest by the way (so it'll be good for 2.3.2)

**Comment by Corail31** [comment]
@Sheppard22 : i'll close this issue, as soon, you confirm me that 'ice & fire' is now compatible with tombstone.

**Comment by Sheppard22** [comment]
Alright i'm expecting to give you that answer today, sorry for the delay, it's just i'm having trouble with my server (freezing mobs/players) since ever and i'm trying to catch the mod that is doing this, anyways i will have your answer today!

**Comment by Sheppard22** [comment]
Hi. The bug is still there, the grave is replaced by charredstone. If the dragon incinerates and kills you, the grave is replaced. Hoowever, in the last try something reaaaaally curious happened to me. I had a sword and full set of Diamond armor. The dragon incinerated me and i lost my grave, but.. I used my minimap mod to tp just where i died (VoxelMap) and it left me inside the charred stone. Somehow i got my sword, helmet and chestplate. Yeah... weird as f.

**Comment by Sheppard22** [comment]
So... i'll try some more times and see if i can reproduce that xD

**Comment by Sheppard22** [comment]
I was incinerated again, the grave disappeared but now i saw the items on the floor. Curious thing is, i got again just the sword, helmet and chestplate.

**Comment by Sheppard22** [comment]
So.... i have an idea. The grave is destroyed and the items get out of there, but then they are broken by the fire!

**Comment by Corail31** [comment]
So, to clarify this bug : 
This is a bug from 'ice & fire'' & i tried to fix with the event.
But this mod seems compltely broken because he replaces block to charred ones without any check, and have changed the ender dragon code that have this check... so i suppose the modder has done this intentionnaly and i'll make this mod incompatible (sorry)

**Comment by Corail31** [comment]
@Sheppard22 I finally got a fix to make the mod compatible.
I'll publish it probably today.

**Comment by Sheppard22** [comment]
That's great! I'll send you a message in private on curse
